#######################################################################
# 
# This uses Ansible's built-in functionality to change a user password
# across multiple systems.
# 
#######################################################################

- hosts: temp
  vars_prompt:
    - name: "user"
      prompt: "User affected"
      private: no

    - name: "newpassword"
      prompt: "New password"
      private: yes

  tasks:
    - name: "Change user password"
      user:
        name: "{{ user }}"
        update_password: always
        password: "{{ newpassword | password_hash('sha512') }}"
      become: true
