#######################################################################
# 
# This approves and installs all needed updates on Debian machines. It
# also automatically removes any unneeded apt packages. 
# 
#######################################################################

- name: Install upgrades
  hosts: debian

  tasks:
    # updates packages
    - name: "Install all available package upgrades"
      apt:
        upgrade: yes
        update_cache: true
      become: true

    # removes unneeded packages
    - name: "Autoremove unneeded packages"
      apt: 
        autoremove: true
        purge: true
      become: true
