###############################################################################
# Reboot all servers in the list. Sometimes hangs for a bit as the reboot     #
# interrupts the connection.                                                  #
###############################################################################

---
- name: rebootServers
  hosts: linux
  become: true

  tasks:
    - name: "Rebooting Server/s"
      reboot:
